SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

ASTEROID_MIN_RADIUS = 15
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 12
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 150
PLAYER_SHOOT_SPEED = 375

SHOT_RADIUS = 4
